apiVersion: v1
kind: Secret
metadata:
  name: mbc-secret
  namespace: skax-eatool
  labels:
    app: mbc
    component: secret
type: Opaque
data:
  # Base64 encoded values
  SPRING_DATASOURCE_PASSWORD: "" 