apiVersion: v1
kind: Service
metadata:
  name: mbc-service
  namespace: skax-eatool
  labels:
    app: mbc
    component: service
spec:
  type: ClusterIP
  ports:
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: http
  - port: 8085
    targetPort: 8085
    protocol: TCP
    name: h2-console
  selector:
    app: mbc
    component: backend 