version: '3.8'

services:
  # API Gateway Service
  api-gateway:
    build:
      context: ./spring-cloud-apigateway-service
      dockerfile: Dockerfile
    container_name: skax-api-gateway
    ports:
      - "8000:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms512m -Xmx1024m
    depends_on:
      - mbc-service
      - mba-service
    networks:
      - skax-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MBC Service
  mbc-service:
    build:
      context: ./mbc-java
      dockerfile: Dockerfile
    container_name: skax-mbc-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - skax-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # MBA Service
  mba-service:
    build:
      context: ./mba-java
      dockerfile: Dockerfile
    container_name: skax-mba-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - skax-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # KSA Service (옵션)
  ksa-service:
    build:
      context: ./ksa-java
      dockerfile: Dockerfile
    container_name: skax-ksa-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - skax-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # KJI Service (옵션)
  kji-service:
    build:
      context: ./kji-java
      dockerfile: Dockerfile
    container_name: skax-kji-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms512m -Xmx1024m
    networks:
      - skax-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  skax-network:
    driver: bridge

volumes:
  mbc-data:
  mba-data: 