apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: skax-eatool
  labels:
    app: registry-config
data:
  # 로컬 레지스트리 설정
  REGISTRY_HOST: "localhost"
  REGISTRY_PORT: "5000"
  REGISTRY_URL: "localhost:5000"
  
  # 내부 클러스터 레지스트리 설정
  INTERNAL_REGISTRY_HOST: "registry.skax-eatool.svc.cluster.local"
  INTERNAL_REGISTRY_PORT: "5000"
  INTERNAL_REGISTRY_URL: "registry.skax-eatool.svc.cluster.local:5000" 