apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
  namespace: skax-eatool
  labels:
    app: apigateway
    component: config
data:
  # Application Configuration
  SERVER_PORT: "8000"
  SPRING_APPLICATION_NAME: "apigateway-service"
  
  # Spring Cloud Gateway Configuration
  SPRING_CLOUD_GATEWAY_DEFAULT_FILTERS_0_NAME: "GlobalFilter"
  SPRING_CLOUD_GATEWAY_DEFAULT_FILTERS_0_ARGS_BASEMESSAGE: "Spring Cloud Gateway Global Filter"
  SPRING_CLOUD_GATEWAY_DEFAULT_FILTERS_0_ARGS_PRELOGGER: "true"
  SPRING_CLOUD_GATEWAY_DEFAULT_FILTERS_0_ARGS_POSTLOGGER: "true"
  
  # JWT Token Configuration
  TOKEN_SECRET: "user_token_secret_key_for_jwt_validation"
  
  # Management Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  
  # Logging Configuration
  LOGGING_LEVEL_COM_EXAMPLE_APIGATEWAYSERVICE: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" 