apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  namespace: skax-eatool
  labels:
    app: apigateway
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
      component: backend
  template:
    metadata:
      labels:
        app: apigateway
        component: backend
    spec:
      containers:
      - name: apigateway-app
        image: skax-eatool/apigateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: apigateway-config
        - secretRef:
            name: apigateway-secret
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      restartPolicy: Always 