apiVersion: v1
kind: Secret
metadata:
  name: apigateway-secret
  namespace: skax-eatool
  labels:
    app: apigateway
    component: secret
type: Opaque
data:
  # Base64 encoded values
  TOKEN_SECRET: dXNlcl90b2tlbl9zZWNyZXRfa2V5X2Zvcl9qd3RfdmFsaWRhdGlvbg== 