

server:
  port: 8000
#===========================================================
spring:
  application:
    name: apigateway-service
#-------Filter 적용 --- start
# 막은사유는 필터를 java code로 변경해서 막음
# FilterConfig.java에 설정    
#  cloud:
#    uri: http://127.0.0.1:8888
#    name: ecommerce    
#    gateway:
#      default-filters:
#        - name: GlobalFilter
#          args:
#            baseMessage: Spring Cloud Gateway Global Filter
#            preLogger: true
#            postLogger: true    
#      routes:
#        - id: first-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/first-service/**
#          filters:
#              - CustomFilter     
#        - id: second-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/second-service/**
#          filters:
#            - name: CustomFilter
#            - name: LoggingFilter
#              args:
#                baseMessage: Hi, there.
#                preLogger: true
#                postLogger: true                             
#        - id: third-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/third-service/**
#          filters:
#            - CustomFilter     
#-------Filter 적용 --- end