name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to rollback'
        required: true
        type: choice
        options:
        - development
        - staging
        - production
      deployment:
        description: 'Deployment to rollback'
        required: true
        type: choice
        options:
        - kji
        - ksa
        - mba
        - mbc
        - mbc01
        - apigateway
        - all

env:
  NAMESPACE: skax-eatool

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
        
    - name: Configure kubectl
      run: |
        if [ "${{ github.event.inputs.environment }}" = "development" ]; then
          echo "${{ secrets.KUBE_CONFIG_DEV }}" | base64 -d > kubeconfig.yaml
        elif [ "${{ github.event.inputs.environment }}" = "staging" ]; then
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > kubeconfig.yaml
        elif [ "${{ github.event.inputs.environment }}" = "production" ]; then
          echo "${{ secrets.KUBE_CONFIG_PROD }}" | base64 -d > kubeconfig.yaml
        fi
        export KUBECONFIG=kubeconfig.yaml
        
    - name: Rollback deployment
      run: |
        chmod +x ./scripts/rollback.sh
        ./scripts/rollback.sh ${{ github.event.inputs.environment }} ${{ github.event.inputs.deployment }}
        
    - name: Verify rollback
      run: |
        chmod +x ./scripts/verify-rollback.sh
        ./scripts/verify-rollback.sh ${{ github.event.inputs.environment }} ${{ github.event.inputs.deployment }}
        
    - name: Send rollback notification
      uses: 8398a7/action-slack@v3
      with:
        status: success
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        text: |
          Rollback completed successfully
          Environment: ${{ github.event.inputs.environment }}
          Deployment: ${{ github.event.inputs.deployment }}
          Triggered by: ${{ github.actor }} 