apiVersion: v1
kind: Service
metadata:
  name: mba-service
  namespace: skax-eatool
  labels:
    app: mba
    component: service
spec:
  type: ClusterIP
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: h2-console
  selector:
    app: mba
    component: backend 