apiVersion: v1
kind: ConfigMap
metadata:
  name: ksa-config
  namespace: skax-eatool
  labels:
    app: ksa
    component: config
data:
  # Application Configuration
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  SERVER_SERVLET_CONTEXT_PATH: "/ksa"
  
  # Database Configuration
  SPRING_DATASOURCE_URL: "jdbc:h2:mem:ksadb"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
  SPRING_DATASOURCE_USERNAME: "sa"
  
  # H2 Console Configuration
  SPRING_H2_CONSOLE_ENABLED: "true"
  SPRING_H2_CONSOLE_PATH: "/h2-console"
  
  # JPA Configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "create-drop"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.H2Dialect"
  
  # Security Configuration
  SPRING_SECURITY_USER_NAME: "admin"
  SPRING_SECURITY_USER_ROLES: "ADMIN"
  
  # Management Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  
  # Logging Configuration
  LOGGING_LEVEL_COM_SKAX_EATOOL_KSA: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 