name: Security Scan

on:
  schedule:
    - cron: '0 2 * * *'  # 매일 새벽 2시
  workflow_dispatch:
  push:
    branches: [ main, develop ]

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'SKAX EATool Eplaton'
        path: '.'
        format: 'HTML'
        out: 'reports'
        args: >
          --failOnCVSS 7
          --enableRetired
          
    - name: Upload dependency check results
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: reports/
        retention-days: 30

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'
        
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  container-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [kji, ksa, mba, mbc, mbc01, apigateway]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build container image
      run: |
        docker build -t ${{ matrix.module }}:${{ github.sha }} ./${{ matrix.module }}-java
        
    - name: Run Trivy container scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ matrix.module }}:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-container-${{ matrix.module }}.sarif'
        
    - name: Upload container scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-container-${{ matrix.module }}.sarif'

  snyk-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/java@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high

  notify-security:
    runs-on: ubuntu-latest
    needs: [dependency-check, trivy-scan, container-scan, snyk-scan]
    if: always()
    steps:
    - name: Send security scan notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#security'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        text: |
          Security scan completed
          Status: ${{ needs.dependency-check.result }} / ${{ needs.trivy-scan.result }} / ${{ needs.container-scan.result }} / ${{ needs.snyk-scan.result }}
          Repository: ${{ github.repository }}
          Branch: ${{ github.ref }} 