server:
  port: 8087
  servlet:
    context-path: /mbb

spring:
  application:
    name: z-generated-files
  
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # Thymeleaf 설정
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

# Swagger 설정
springfox:
  documentation:
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

# 로깅 설정
logging:
  level:
    com.skax.eatool: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 생성된 파일 관리 설정
generated:
  files:
    base-path: ./generated-files
    backup-enabled: true
    version-control: true
    auto-cleanup: false
    cleanup-days: 30 