# MBA (Master Business Application) Configuration
spring:
  application:
    name: MBA-SERVICE
  
  profiles:
    active: dev
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:mbadb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 Console Configuration (for development)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  
  # Jackson Configuration
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    default-property-inclusion: NON_NULL

# Server Configuration
server:
  port: 8084
  servlet:
    context-path: /mba
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Eureka Client Configuration (비활성화)
eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    enabled: false

# Logging Configuration
logging:
  level:
    com.skax.eatool.mba: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mba-application.log

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: MBA API Documentation

# MBC Service Configuration for TPSsendrecv
mbc:
  service:
    url: http://localhost:8085
    context-path: /mbc

# Application Specific Configuration
mba:
  app:
    name: Master Business Application
    version: 1.0.0
    description: 마스터 비즈니스 애플리케이션
  security:
    jwt:
      secret: mba-jwt-secret-key-2024
      expiration: 86400000 # 24 hours
  database:
    schema: mba_schema
    data: mba_data 