apiVersion: v1
kind: Secret
metadata:
  name: mbc01-secret
  namespace: skax-eatool
  labels:
    app: mbc01
    component: secret
type: Opaque
data:
  # Base64 encoded values
  SPRING_DATASOURCE_PASSWORD: "" 