apiVersion: v1
kind: Service
metadata:
  name: kji-service
  namespace: skax-eatool
  labels:
    app: kji
    component: service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: h2-console
  selector:
    app: kji
    component: backend 